# Monitor
monitor=,preferred,auto,1

# Startup
exec-once = hyprpaper & dunst

# Programs
$terminal = kitty
$browser = brave
$menu = wofi --show drun

bind = SUPER, Q, exec, $terminal
bind = SUPER, E, exec, $browser
bind = SUPER, SPACE, exec, $menu
bind = SUPER, C, killactive,
bind = SUPER, F, fullscreen,
bind = SUPER, L, exec, hyprlock
bind = SUPER, V, togglefloating,

# Screenshots
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy

# Volume
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Workspace switching
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9

# General
general {
  gaps_in = 5
  gaps_out = 10
  border_size = 2
  col.active_border = rgba(33ccffee)
  col.inactive_border = rgba(595959aa)
  layout = dwindle
}

# Decoration
decoration {
  rounding = 10
  blur = true
  blur_size = 3
  blur_passes = 1
}

# Input
# Animations
bezier = snappy, 0.05, 0.9, 0.1, 1.05

animation = windows, 1, 3, snappy
animation = windowsOut, 1, 3, snappy
animation = fade, 1, 3, snappy
animation = workspaces, 1, 2, snappy
animation = border, 1, 5, default

input {
  kb_layout = es
  follow_mouse = 1
}
